version: "3"
services:
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  pratica_cicd:
    container_name: pratica_cicd
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db_test
